version: "3.3"

services:
  naas:
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile.dev
    environment:
        "ALLOWED_IFRAME": ""
        JUPYTER_TOKEN: 'naas'
        JUPYTERHUB_URL: 'http://localhost:8888'
        PROD_JUPYTERHUB_API_TOKEN: ${PROD_JUPYTERHUB_API_TOKEN}
    ports:
      - 8888:8888
      - 5000:5000
      - 38745:38745
    volumes:
      - ~/.ssh:/home/ftp/.ssh
      - .:/home/ftp/naas
      - ../drivers:/home/ftp/drivers
      - ../awesome-notebooks:/home/ftp/awesome-notebooks
      - ../drivers/naas_drivers:/opt/conda/lib/python3.8/site-packages/naas_drivers
      - ./file_sharing:/home/ftp/file_sharing
      - .docker/.cache/pip:/home/jovyan/.cache/pip
      - .docker/dev/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./custom/overrides.json:/opt/conda/share/jupyter/lab/settings/overrides.json
