#!/usr/bin/env bash

set -x

BUILD="YES"
SUPP="NO"
N_ENV="dev"
RUN="NO"
TOKEN="naas"
for i in "$@"
do

case $i in
    -ro|--run-only)
    BUILD="NO"
    RUN="YES"
    shift # past argument=value
    ;;
    -s|--supp)
    SUPP="YES"
    shift # past argument=value
    ;;
    -p|--prod)
    N_ENV="prod"
    shift # past argument=value
    ;;
    -r|--run)
    RUN="YES"
    shift # past argument=value
    ;;
    -t=*|--token=*)
    TOKEN="${i#*=}"
    shift # past argument=value
    ;;
    *)
    echo "UNRECONIZED ARGUMENT"
    exit
    ;;
esac
done

setCrossPlatformVolumeParameter() 
{
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo $1:z
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo $1
    else
        echo $1
    fi
}

VOLUME_SSH=$(setCrossPlatformVolumeParameter "$HOME/.ssh:/home/ftp/.ssh")
VOLUME_NAAS=$(setCrossPlatformVolumeParameter "$PWD:/home/ftp/naas")

if [[ $BUILD == "YES" ]]; then
    docker pull jupyternaas/singleuser:latest
    if docker build -f Dockerfile.$N_ENV --build-arg INSTALL_SUPP=$SUPP -t jupyternaas/naas:local_$N_ENV . ; then
        echo "Build succeeded"
    else
        echo "Build failed"
        exit
    fi
fi

if [[ $RUN == "YES" ]]; then
    echo "============================= RUN Naas ============================="
    docker stop naas_$N_ENV
    docker rm $(docker ps -aq --filter name=naas_$N_ENV)
    docker run \
        --name naas_$N_ENV \
        -e ALLOWED_IFRAME='' \
        -e ALLOWED_IFRAME='' \
        -e JUPYTER_TOKEN="$TOKEN" \
        -e JUPYTERHUB_URL='http://localhost:8888' \
        -p 8888:8888 \
        -p 5000:5000 \
        -v "$VOLUME_NAAS" \
        -v "$VOLUME_SSH" \
        jupyternaas/naas:local_$N_ENV
fi