#!/usr/bin/env bash

if [[ $NAAS_INSTALL_SUPP == "yes" ]]; then
    cd /home/$NB_USER
    git clone https://github.com/jupyter-naas/drivers.git
    cd /home/$NB_USER/drivers
    pip install -e '.[dev]'
    cd /home/$NB_USER
    git clone https://github.com/jupyter-naas/awesome-notebooks.git
else
    echo "Not install"
fi
