#!/bin/bash
set -euo pipefail

mkdir -p binder-demo

# Enable debug output
set -x

# Add getting started assets to Docker image
# (1) Clone the examples repository.
git clone https://github.com/jupyter-naas/starters.git

EXAMPLES_BASE_DIR=starters

# (2) Copy all getting started assets to the working directory,
#     which is referenced when binder is invoked, e.g. 
#     https://mybinder.org/v2/gh/elyra-ai/elyra/master?urlpath=lab/tree/binder-demo
cp -r $EXAMPLES_BASE_DIR/* binder-demo/

# (5) Remove cloned examples directory
rm -rf $EXAMPLES_BASE_DIR
